import banana from '../images/banana.png'
import berry from '../images/berry.png'
import chery from '../images/chery.png'
import yogurt from '../images/yogurt.png'
export const foodCategories = [
    "Produce",
    "Dairy",
    "Bakery",
    "Frozen",
    "Canned",
    "Snacks",
    "Beverages",
    "Pasta",
    "Condiments",
    "Seafood",
    "Deli",
    "Sweets",
    "Breakfast",
    "Desserts",
    "Spices",
    "Organic",
    "Gluten",
    "Vegan",
    "Vegetarian",
    "Cuisine"
  ];
  const  dummyData = [
    {
      title: "Produce",
      data: [
        {
          id:1,
          image: banana,
          name: "Banana 1 ct",
          price:0.69,
          newPrice:null,
          cal: "18 oz",
        },
        {
          id:2,
          image: chery,
          name: "Strawberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:3,
          image: yogurt,
          name: "Yogurt",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:4,
          image: berry,
          name: "Blackberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:1,
          image: banana,
          name: "Banana 1 ct",
          price:0.69,
          newPrice:null,
          cal: "18 oz",
        },
        {
          id:2,
          image: chery,
          name: "Strawberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:3,
          image: yogurt,
          name: "Yogurt",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:4,
          image: berry,
          name: "Blackberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        }, {
          id:1,
          image: banana,
          name: "Banana 1 ct",
          price:0.69,
          newPrice:null,
          cal: "18 oz",
        },
        {
          id:2,
          image: chery,
          name: "Strawberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:3,
          image: yogurt,
          name: "Yogurt",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:4,
          image: berry,
          name: "Blackberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        }, {
          id:1,
          image: banana,
          name: "Banana 1 ct",
          price:0.69,
          newPrice:null,
          cal: "18 oz",
        },
        {
          id:2,
          image: chery,
          name: "Strawberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:3,
          image: yogurt,
          name: "Yogurt",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:4,
          image: berry,
          name: "Blackberries",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
      ],
    },
    {
      title: "Dairy",
      data: [
        {
          id:2,
          image: chery, 
          name: "Milk",
          price:0.69,
          newPrice:null,
          cal: "1 gallon",
        },
        {
          id:1,
          image: banana, 
          name: "Cheese",
          price:0.69,
          newPrice:null,
          cal: "8 oz",
        },
        {
          id:3,
          image: yogurt, 
          name: "Yogurt",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
      ],
    },
    {
      title: "Bakery",
      data: [
        {
          id:3,
          image: yogurt, 
          name: "Bread",
          price:0.69,
          newPrice:null,
          cal: "16 oz",
        },
        {
          id:1,
          image: banana, 
          name: "Baguette",
          price:0.69,
          newPrice:null,
          cal: "8 oz",
        },
        {
          id:4,
          image: berry, 
          name: "Croissant",
          price:0.69,
          newPrice:null,
          cal: "3 oz",
        },
      ],
    },
    {
      title: "Frozen",
      data: [
        {
          id:3,
          image: yogurt, 
          name: "Chicken Breast",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:2,
          image: chery, 
          name: "Beef Steak",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:4,
          image: berry, 
          name: "Pork Chops",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
      ],
    },
    {
      title: "Canned",
      data: [
        {
          id:3,
          image: yogurt, 
          name: "Soup",
          price:0.69,
          newPrice:null,
          cal: "15 oz",
        },
        {
          id:1,
          image: banana, 
          name: "Baked Beans",
          price:0.69,
          newPrice:null,
          cal: "16 oz",
        },
        {
          id:4,
          image: berry, 
          name: "Canned Tomatoes",
          price:0.69,
          newPrice:null,
          cal: "28 oz",
        },
      ],
    },
    {
      title: "Snacks",
      data: [
        {
          id:1,
          image: banana, 
          name: "Potato Chips",
          price:0.69,
          newPrice:null,
          cal: "8 oz",
        },
        {
          id:2,
          image: chery, 
          name: "Chocolate Cookies",
          price:0.69,
          newPrice:null,
          cal: "12 oz",
        },
        {
          id:3,
          image: yogurt, 
          name: "Mixed Nuts",
          price:0.69,
          newPrice:null,
          cal: "10 oz",
        },
      ],
    },
    {
      title: "Beverages",
      data: [
        {
          id:3,
          image: yogurt, 
          name: "Soda",
          price:0.69,
          newPrice:null,
          cal: "2 liters",
        },
        {
          id:2,
          image: chery, 
          name: "Orange Juice",
          price:0.69,
          newPrice:null,
          cal: "64 oz",
        },
        {
          id:4,
          image: berry, 
          name: "Bottled Water",
          price:0.69,
          newPrice:null,
          cal: "16.9 oz",
        },
      ],
    },
    {
      title: "Pasta",
      data: [
        {
          id:1,
          image: banana, 
          name: "Spaghetti Pasta",
          price:0.69,
          newPrice:null,
          cal: "16 oz",
        },
        {
          id:2,
          image: chery, 
          name: "White Rice",
          price:0.69,
          newPrice:null,
          cal: "2 lb",
        },
        {
          id:3,
          image: yogurt, 
          name: "Quinoa",
          price:0.69,
          newPrice:null,
          cal: "12 oz",
        },
      ],
    },
    {
      title: "Condiments",
      data: [
        {
          id:3,
          image: yogurt, 
          name: "Ketchup",
          price:0.69,
          newPrice:null,
          cal: "20 oz",
        },
        {
          id:1,
          image: banana, 
          name: "Mayonnaise",
          price:0.69,
          newPrice:null,
          cal: "32 oz",
        },
        {
          id:4,
          image: berry, 
          name: "Mustard",
          price:0.69,
          newPrice:null,
          cal: "14 oz",
        },
      ],
    },
    {
      title: "Seafood",
      data: [
        {
          id:1,
          image: banana, 
          name: "Salmon Fillet",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:2,
          image: chery, 
          name: "Shrimp",
          price:0.69,
          newPrice:0.69,
          cal: "1 lb",
        },
        {
          id:4,
          image: berry, 
          name: "Canned Tuna",
          price:0.69,
          newPrice:null,
          cal: "12 oz",
        },
      ],
    },
    {
      title: "Deli",
    data: [
      {
        id:3,
        image: yogurt, 
        name: "Deli Ham",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
      {
        id:1,
        image: banana, 
        name: "Turkey Breast",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
      {
        id:4,
        image: berry, 
        name: "Swiss Cheese",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
    ],
  },
  {
    title: "Sweets",
    data: [
      {
        id:1,
        image: banana, 
        name: "Chocolate Bar",
        price:0.69,
        newPrice:null,
        cal: "3 oz",
      },
      {
        id:2,
        image: chery, 
        name: "Assorted Candy",
        price:0.69,
        newPrice:null,
        cal: "10 oz",
      },
      {
        id:3,
        image: yogurt, 
        name: "Ice Cream",
        price:0.69,
        newPrice:null,
        cal: "1 pint",
      },
    ],
  },
  {
    title: "Breakfast",
    data: [
      {
        id:3,
        image: yogurt, 
        name: "Breakfast Cereal",
        price:0.69,
        newPrice:null,
        cal: "12 oz",
      },
      {
        id:1,
        image: banana, 
        name: "Eggs",
        price:0.69,
        newPrice:null,
        cal: "1 dozen",
      },
      {
        id:2,
        image: chery, 
        name: "Toasted Bread",
        price:0.69,
        newPrice:null,
        cal: "16 oz",
      },
    ],
  },
  {
    title: "Desserts",
    data: [
      {
        id:3,
        image: yogurt, 
        name: "Chocolate Cake",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
      {
        id:1,
        image: banana, 
        name: "Apple Pie",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
      {
        id:4,
        image: berry, 
        name: "Cookies",
        price:0.69,
        newPrice:null,
        cal: "10 oz",
      },
    ],
  },
  {
    title: "Spices",
    data: [
      {
        id:2,
        image: chery, 
        name: "Salt",
        price:0.69,
        newPrice:null,
        cal: "16 oz",
      },
      {
        id:3,
        image: yogurt, 
        name: "Black Pepper",
        price:0.69,
        newPrice:null,
        cal: "3 oz",
      },
      {
        id:1,
        image: banana, 
        name: "Fresh Basil",
        price:0.69,
        newPrice:null,
        cal: "4 oz",
      },
    ],
  },
  {
    title: "Organic",
    data: [
      {
        id:2,
        image: chery, 
        name: "Organic Apples",
        price:0.69,
        newPrice:0.69,
        cal: "1 lb",
      },
      {
        id:1,
        image: banana, 
        name: "Organic Carrots",
        price:0.69,
        newPrice:0.69,
        cal: "1 lb",
      },
      {
        id:4,
        image: berry, 
        name: "Organic Spinach",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
    ],
  },
  {
    title: "Gluten",
    data: [
      {
        id:3,
        image: yogurt, 
        name: "Gluten Bread",
        price:0.69,
        newPrice:null,
        cal: "16 oz",
      },
      {
        id:2,
        image: chery, 
        name: "Gluten Pasta",
        price:0.69,
        newPrice:null,
        cal: "12 oz",
      },
      {
        id:1,
        image: banana, 
        name: "Gluten Cake",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
    ],
  },
  {
    title: "Vegan",
    data: [
      {
        id:2,
        image: chery, 
        name: "Vegan Burgers",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
      {
        id:1,
        image: banana, 
        name: "Vegan Milk",
        price:0.69,
        newPrice:null,
        cal: "1 quart",
      },
      {
        id:4,
        image: berry, 
        name: "Vegan Cheese",
        price:0.69,
        newPrice:null,
        cal: "8 oz",
      },
    ],
  },
  {
    title: "Vegetarian",
    data: [
      {
        id:3,
        image: yogurt, 
        name: "Vegetarian Lasagna",
        price:0.69,
        newPrice:0.69,
        cal: "1 lb",
      },
      {
        id:1,
        image: banana, 
        name: "Vegetarian Burrito",
        price:0.69,
        newPrice:null,
        cal: "12 oz",
      },
      {
        id:2,
        image: chery, 
        name: "Vegetarian Pizza",
        price:0.69,
        newPrice:null,
        cal: "14 oz",
      },
    ],
  },
  {
    title: "Cuisine",
    data: [
      {
        id:1,
        image: banana, 
        name: "Sushi",
        price:0.69,
        newPrice:null,
        cal: "16 pieces",
      },
      {
        id:2,
        image: chery, 
        name: "Taco Kit",
        price:0.69,
        newPrice:null,
        cal: "1 kit",
      },
      {
        id:4,
        image: berry, 
        name: "Curry Sauce",
        price:0.69,
        newPrice:null,
        cal: "16 oz",
      },
    ],
  },
  ];
  

  function generateUniqueIds(data) {
    let idCounter = 1;
  
    for (const category of data) {
      for (const item of category.data) {
        item.id = idCounter++;
      }
    }
  }
   generateUniqueIds(dummyData);
 export const data= dummyData;